language: python
jobs:
  include:
    - name: "Python 3.6 on Linux"
      os: linux
      dist: xenial
      python: 3.6
    - name: "Python 3.6 on MacOS"
      os: osx
      language: generic
    - name: "Python 3.7 on Linux"
      os: linux
      dist: xenial
      python: 3.7
    - name: "Python 3.7 on MacOS"
      os: osx
      language: generic
install: pip3 install --upgrade pip
script:
  - pytest genomics_algo/tests/
