name: CI


on:
  pull_request:
    branches: [main]
  push:
    branches:
      - '*'
  schedule:
    # daily (`@daily` not supported, see
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events )
    #
    # Runs on default/base branch (see
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule )
    - cron: '0 0 * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip install -r reqs.txt
          pip install -e .
      - name: Run tests
        run: py.test --doctest-modules -vv genomics_algo/
      - name: Formatting with black
        run: |
          pip install black
          black --check genomics_algo/
